import { Router } from 'express';

export const documentationRouter = Router();

documentationRouter.get('/mcp/context', (_request, response) => {
  response.json({
    name: 'pdfme-server',
    purpose: 'Servicio para administrar plantillas PDF, publicar versiones y generar documentos por API.',
    audience: ['IA asistente', 'integradores API', 'desarrolladores externos'],
    security: {
      public: 'La documentacion y este contexto son publicos. No exponen usuarios, claves API, plantillas privadas ni datos renderizados.',
      authentication: 'La API operativa usa x-api-key. La app administrativa usa cookie de sesion HTTP-only.',
    },
    api: {
      basePath: '/api',
      externalBasePath: '/api/v1',
      authHeader: 'x-api-key',
      coreRule: 'La API entrega valores; la plantilla define como se representan. input no contiene instrucciones visuales.',
      endpoints: [
        { method: 'GET', path: '/api/v1/templates', description: 'Lista plantillas no archivadas disponibles para integracion.' },
        { method: 'GET', path: '/api/v1/templates/:code/inputs', description: 'Devuelve variables y objetos cambiables esperados por una plantilla.' },
        { method: 'POST', path: '/api/v1/render', description: 'Genera un PDF desde templateCode e input.' },
      ],
      internalPanelApi: {
        authentication: 'Usa cookie de sesion HTTP-only creada por /api/auth/login. No usa x-api-key.',
        permissions: 'Cada ruta interna aplica requirePermission segun el area administrativa.',
        endpoints: [
          { method: 'GET', path: '/api/templates?search=&tag=', permission: 'templates.view', description: 'Lista plantillas internas con busqueda por name/code y filtro por etiqueta.' },
          { method: 'GET', path: '/api/templates/by-code/:code', permission: 'templates.view', description: 'Carga una plantilla completa para editor o preview.' },
          { method: 'POST', path: '/api/templates', permission: 'templates.create', description: 'Crea plantilla inicial.' },
          { method: 'POST', path: '/api/templates/:id/duplicate', permission: 'templates.create', description: 'Duplica plantilla con version, hojas, diseno y etiquetas.' },
          { method: 'PATCH', path: '/api/templates/:id', permission: 'templates.edit', description: 'Actualiza name, code y tagNames.' },
          { method: 'PATCH', path: '/api/templates/:id/page-settings', permission: 'templates.edit', description: 'Guarda formato, tamano y designerJson completo.' },
          { method: 'PATCH', path: '/api/templates/:id/schema-locks', permission: 'templates.edit', description: 'Persiste bloqueos de elementos en designerJson usando lockedSchemaNames.' },
          { method: 'POST', path: '/api/templates/:id/versions', permission: 'templates.edit', description: 'Crea una version nueva.' },
          { method: 'PATCH', path: '/api/templates/:id/versions/:versionId/current', permission: 'templates.edit', description: 'Marca una version como actual.' },
          { method: 'DELETE', path: '/api/templates/:id/versions/:versionId', permission: 'templates.edit', description: 'Elimina una version si no es la unica y renumera las restantes.' },
          { method: 'DELETE', path: '/api/templates/:id', permission: 'templates.delete', description: 'Elimina una plantilla completa.' },
          { method: 'GET', path: '/api/tags', permission: 'templates.edit', description: 'Lista etiquetas.' },
          { method: 'POST', path: '/api/tags', permission: 'templates.edit', description: 'Crea etiqueta.' },
          { method: 'PATCH', path: '/api/tags/:id', permission: 'templates.edit', description: 'Renombra etiqueta.' },
          { method: 'DELETE', path: '/api/tags/:id', permission: 'templates.edit', description: 'Elimina etiqueta.' },
          { method: 'GET', path: '/api/api-credentials', permission: 'api_keys.manage', description: 'Lista claves API.' },
          { method: 'POST', path: '/api/api-credentials', permission: 'api_keys.manage', description: 'Crea clave API y devuelve rawKey una sola vez.' },
          { method: 'PATCH', path: '/api/api-credentials/:id/disable', permission: 'api_keys.manage', description: 'Deshabilita clave API.' },
          { method: 'PATCH', path: '/api/api-credentials/:id/activate', permission: 'api_keys.manage', description: 'Activa clave API no expirada.' },
          { method: 'PATCH', path: '/api/api-credentials/:id/revoke', permission: 'api_keys.manage', description: 'Revoca o deshabilita clave API.' },
          { method: 'DELETE', path: '/api/api-credentials/:id', permission: 'api_keys.manage', description: 'Elimina clave API.' },
          { method: 'GET', path: '/api/users', permission: 'users.manage', description: 'Lista usuarios y roles.' },
          { method: 'POST', path: '/api/users', permission: 'users.manage', description: 'Crea usuario.' },
          { method: 'PATCH', path: '/api/users/:id', permission: 'users.manage', description: 'Actualiza usuario, rol, estado o password.' },
          { method: 'DELETE', path: '/api/users/:id', permission: 'users.manage', description: 'Elimina usuario con verificacion de password.' },
          { method: 'GET', path: '/api/permissions', permission: 'users.manage', description: 'Devuelve matriz de permisos.' },
          { method: 'PATCH', path: '/api/roles/:id/permissions', permission: 'users.manage', description: 'Actualiza permisos de rol.' },
          { method: 'GET', path: '/api/audit-logs', permission: 'audit.view', description: 'Lista auditoria.' },
          { method: 'GET', path: '/api/health', permission: 'public', description: 'Healthcheck del backend.' },
        ],
        schemaLocks: {
          endpoint: 'PATCH /api/templates/:id/schema-locks',
          payload: { lockedSchemaNames: ['0::fondo_constancia', '1::qr_constancia'] },
          effect: 'Actualiza __isLocked en los schemas de la version actual y lo guarda en base de datos.',
        },
        versionDeletion: 'DELETE /api/templates/:id/versions/:versionId no permite borrar la unica version. Luego de borrar renumera las versiones restantes desde 1 y conserva una version actual.',
        pageActions: 'Insertar, eliminar o mover hojas cambia designerJson en memoria y se persiste con /page-settings al presionar Guardar. Bloquear elementos se persiste inmediatamente con /schema-locks.',
      },
      inputModel: {
        templateCode: 'Codigo estable de plantilla.',
        input: 'Objeto JSON con variables de texto y objetos dinamicos.',
        pages: 'Arreglo opcional con numeros de hojas que deben devolverse. Si se omite, se toma toda la plantilla.',
        ignorePages: 'Arreglo opcional con numeros de hojas que no deben renderizarse. Se aplica despues de pages.',
        variables: 'Las variables se detectan por placeholders como {nombre_participante}. La misma clave se aplica en todas las paginas donde exista.',
        textModes: 'plain imprime texto simple; inline-markdown admite negrita, cursiva, tachado, codigo y enlaces definidos en la plantilla.',
        markdownValues: 'Los valores enviados para variables se insertan como texto literal. El formato Markdown debe definirse alrededor de la variable en la plantilla.',
        dynamicLinks: 'Un enlace puede combinar variables en su etiqueta y destino. Ejemplo: [{codigo_constancia}](https://eventos.miempresa.com/constancias/{codigo_constancia}). input.codigo_constancia contiene solo el codigo.',
        dynamicObjects: 'Los objetos cuyo nombre empieza con # pueden actualizarse por API. Ejemplo: #qr_constancia#1 y #qr_constancia#2 usan input.qr_constancia.',
      },
      contractRules: {
        templateCode: 'Debe ser el campo code devuelto por el catalogo. No debe usarse id, name ni un slug calculado.',
        valuesOnly: 'Cada propiedad de input contiene un valor. No contiene HTML, Markdown, arreglos serializados ni instrucciones visuales.',
        repeatedKeys: 'Una misma variable u objeto normalizado recibe el mismo valor en todas las paginas donde se use.',
        pageSelection: 'pages limita el subconjunto de hojas a devolver; ignorePages excluye hojas de ese subconjunto o del total.',
        missingTextVariables: 'Una variable detectada ausente, null o con cadena vacia produce HTTP 400 y missingVariables.',
        missingDynamicObjects: 'Un objeto dinamico ausente no se incluye en missingVariables y conserva el comportamiento configurado en la plantilla.',
        additionalKeys: 'Una clave que no coincide con una variable, objeto dinamico o nombre interno no modifica la plantilla.',
      },
      componentContracts: {
        textVariable: 'Recibe texto literal. Ejemplo: nombre_participante = ANA TORRES.',
        markdownVariable: 'Recibe el dato que necesita la expresion de la plantilla, no Markdown ni HTML.',
        qrcode: 'Recibe el contenido final que debe codificarse, por ejemplo una URL completa.',
        image: 'Recibe un Data URI o una URL accesible para el backend.',
        date: 'Recibe una fecha en el formato acordado por la plantilla e integracion.',
      },
      example: {
        template: '[{codigo_constancia}](https://eventos.miempresa.com/constancias/{codigo_constancia}) y un objeto qrcode llamado #qr_constancia.',
        request: {
          templateCode: 'constancia_webinar',
          input: {
            nombre_participante: 'ANA TORRES',
            nombre_evento: 'Webinar de gestion de eventos',
            codigo_constancia: 'WEB-2026-001',
            qr_constancia: 'https://eventos.miempresa.com/validar/WEB-2026-001',
          },
          pages: [1, 2, 3],
          ignorePages: [3],
        },
        explanation: 'codigo_constancia contiene solo el codigo porque la plantilla construye el enlace. qr_constancia contiene la URL final porque el componente QR codifica exactamente ese valor.',
      },
      renderResponse: {
        status: 200,
        contentType: 'application/pdf',
        body: 'PDF binario. No es JSON, base64 ni una URL.',
        clientHandling: 'Leer como Buffer o ArrayBuffer. No ejecutar JSON.parse sobre una respuesta exitosa.',
        boundary: 'Guardar, subir, enviar o registrar el PDF corresponde al sistema consumidor.',
      },
      errors: {
        400: 'Payload invalido, variables de texto faltantes, pages/ignorePages con hojas invalidas o seleccion vacia.',
        401: 'API key ausente, invalida, expirada o no autorizada por origen.',
        404: 'Plantilla inexistente, archivada o sin version actual.',
        500: 'Fallo durante la generacion del documento.',
        502: 'Error del proxy o infraestructura; no es una respuesta funcional de la API.',
      },
      dynamicObjectTypes: ['image', 'qrcode', 'code128', 'date', 'dateTime', 'time'],
    },
    documentation: [
      { title: 'Vision general', url: '/documentation/getting-started' },
      { title: 'Plantillas y contenido', url: '/documentation/templates' },
      { title: 'Autenticacion', url: '/documentation/authentication' },
      { title: 'API e integracion', url: '/documentation/api' },
      { title: 'Errores y operacion', url: '/documentation/responses' },
    ],
  });
});
